name: Lint
on:
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22.x

      - name: Verify formatting
        run: |
          make lint
          if [[ -n "$(git status --porcelain | grep -v 'argo-cd\|gitops-engine')" ]]; then
            echo "The following files have formatting issues:"
            git status --porcelain
            echo "Please run 'make lint' locally and commit the changes"
            exit 1
          fi
