name: Create Release
on:
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  create-release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: flanksource/action-workflows/.github/workflows/create-release.yml@f8512a65d38c1ea53d5c83a4e30ee2ae56acac6f # v1.2.1

  goreleaser:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [create-release]
    if: needs.create-release.outputs.published == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: stable

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@e435ccd777264be153ace6237001ef4d979d3a7a # v6.4.0
        with:
          distribution: goreleaser
          version: v2.17.1
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-release:
    permissions:
      contents: write
    needs: [create-release, goreleaser]
    if: needs.create-release.outputs.published == 'true'
    uses: flanksource/action-workflows/.github/workflows/publish-release.yml@f8512a65d38c1ea53d5c83a4e30ee2ae56acac6f # v1.2.1
    with:
      tag: ${{ needs.create-release.outputs.tag }}
    secrets:
      token: ${{ secrets.FLANKBOT }}
