name: Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: v1.22.x 
     
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Test
        run: go test ./...
